    conditions:
        all:
        - fact: payload.issue.title
          operator: regex
          value: ^\[bug\]
        # Prevent loops
        - fact: payload.sender.type
          operator: notEqual
          value: Bot
    event:
        # type: issuesAddLabels
        type: assignIssueToProject
        params:
            data:
            - Kanban2
            - 'To do'
