---
conditions:
  all:
    - fact: payload.issue.user.login
      operator: equal
      value: jefeish
    # Prevent loops
    - fact: payload.sender.type
      operator: notEqual
      value: Bot
event:
  type: createIssueComment
  params:
    data: This is a message from a Repo Rule!
