    conditions:
        all:
        - fact: payload.issue.labels
          operator: contains
          value: 
            - In progress
        # Prevent loops
        - fact: payload.sender.type
          operator: notEqual
          value: Bot
    event:
        # type: issuesAddLabels
        type: assignIssueToProject
        params:
            data:
            - Kanban2
            - In progress
