    conditions:
        all:
        - fact: payload.issue.title
          operator: includes
          value: bug
        # Prevent loops
        - fact: payload.sender.type
          operator: notEqual
          value: Bot
    event:
        type: createIssueLabels
        params:
            data:
            - bug
            - question
