---
# default is '1'
priority: 40
name: "project 'backlog' rule"

conditions:
  all:
    - fact: payload.issue.labels.name
      operator: contains
      value: Backlog
    - fact: payload.issue.state
      operator: notEqual
      value: closed
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Blocked
    # Prevent loops
    - fact: payload.sender.type
      operator: notEqual
      value: Bot

event:
  type: issuesAssignToProject
  params:
    data:
      - Kanban2
      - Backlog
