---
# default is '1'
priority: 10
name: "project 'backlog' rule"

conditions:
  all:
    - fact: payload.issue.labels.name
      operator: contains
      value: Backlog
    - fact: payload.issue.state
      operator: notEqual
      value: closed
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Blocked

event:
  type: assignIssueToProject
  params:
    data:
      - Kanban2
      - Backlog
