---
# default is '1'
priority: 20
name: "project 'blocked'' rule"

conditions:
  all:
    - fact: payload.issue.labels.name
      operator: contains
      value: Blocked
    - fact: payload.issue.state
      operator: notEqual
      value: closed
    # Prevent loops
    - fact: payload.sender.type
      operator: notEqual
      value: Bot

event:
  type: issuesAssignToProject
  params:
    data:
      - Kanban2
      - Blocked
