    conditions:
        all:       
        - fact: payload.issue.labels.name
          operator: contains
          value: Blocked
        # Prevent loops
        - fact: payload.sender.type
          operator: notEqual
          value: Bot
    event:
        type: assignIssueToProject
        params:
            data:
            - Kanban2
            - Blocked
