---
conditions:
  all:
    - fact: payload.issue.assignees.login
      operator: notEmpty
      value: ""
    - fact: payload.issue.labels.name
      operator: contains
      value: In progress
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Blocked

event:
  type: assignIssueToProject
  params:
    data:
      - Kanban2
      - In progress

# default is '1'
priority: 20
