---
# default is '1'
priority: 10
name: "project 'To do' unassigned rule"

conditions:
  all:
    - fact: payload.issue.assignees.login
      operator: isEmpty
      value: ""
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Backlog
    - fact: payload.issue.labels.name
      operator: isNotEmpty
      value: ""
    - fact: payload.issue.state
      operator: notEqual
      value: closed
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Blocked
    # Prevent loops
    - fact: payload.sender.type
      operator: notEqual
      value: Bot

event:
  type: issuesOverrideLabel
  params:
    data:
      - In progress
      - To do
