---
conditions:
  all:
    - fact: payload.issue.state
      operator: equal
      value: closed

event:
  type: assignIssueToProject
  params:
    data:
      - Kanban2
      - Done
# default is '1'
priority: 10
