---
# default is '1'
priority: 80
name: "project todo rule"

conditions:
  all:
    - fact: payload.issue.assignees.login
      operator: isEmpty
      value: ""
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Backlog
    - fact: payload.issue.state
      operator: notEqual
      value: closed
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Blocked

event:
  type: issuesReplaceLabels
  params:
    data:
      - To do
