---
# default is '1'
priority: 10
name: "project 'In progress' by assignees rule"

conditions:
  all:
    - fact: payload.issue.labels.name
      operator: contains
      value: In progress
    - fact: payload.issue.state
      operator: notEqual
      value: closed
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Blocked
    # Prevent loops
    - fact: payload.sender.type
      operator: notEqual
      value: Bot

event:
  type: issuesAssignToProject
  params:
    data:
      - Kanban2
      - In progress
