---
conditions:
  all:
    - fact: payload.issue.state
      operator: equal
      value: closed

event:
  type: issuesRemoveLabels
  params:
    data:
      - Backlog
      - To do
      - In progress
      - Blocked

# default is '1'
priority: 10
