---
# default is '1'
priority: 40
name: "project 'In progress' by assignees rule"

conditions:
  all:
    - fact: payload.issue.assignees.login
      operator: notEmpty
      value: ""
    - fact: payload.issue.state
      operator: notEqual
      value: closed
    - fact: payload.issue.labels.name
      operator: doesNotContain
      value: Blocked

event:
  type: issuesReplaceLabels
  params:
    data:
      - In progress
