---
conditions:
  all:
    - fact: payload.issue.state
      operator: equals
      value: closed
    # Prevent loops
    - fact: payload.sender.type
      operator: notEqual
      value: Bot
event:
  type: assignIssueToProject
  params:
    data:
      - Kanban2
      - Done
