---
conditions:
  all:
    - fact: payload.issue.state
      operator: doesNotInclude
      value: open
    # Prevent loops
    - fact: payload.sender.type
      operator: notEqual
      value: Bot
event:
  type: issuesRemoveLabels
  params:
    data:
      - Blocked
      - To do
      - Backlog
